---
- name: Configure Web Server and Install Docker
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is running and enabled
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to the docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Copy the app folder to the EC2 instance
      copy:
        src: ../app
        dest: /home/ubuntu/
        owner: ubuntu

    - name: Copy the Dockerfile to the EC2 instance
      copy:
        src: ../Dockerfile
        dest: /home/ubuntu/
        owner: ubuntu

    - name: Build the Docker image
      command: docker build -t my-website /home/ubuntu/

    - name: Run the Docker container
      command: docker run -d -p 80:80 --name running-site my-website
